gcp_project   = "project-b85b49c5-5bdc-48ac-989"
region        = "europe-west1"
client_slug   = "beta-corp"
domain        = "beta.nomowsoft.com"
database_name = "beta"
admin_user    = "admin@beta-corp.com"
image_url     = "europe-west1-docker.pkg.dev/project-b85b49c5-5bdc-48ac-989/odoo-v18-repo/odoo-pooled:latest"
