gcp_project   = "project-b85b49c5-5bdc-48ac-989"
region        = "europe-west1"
client_slug   = "mac-corp"
domain        = "mac.nomowsoft.com"
database_name = "mac"
admin_user    = "admin@mac-corp.com"
image_url     = "europe-west1-docker.pkg.dev/project-b85b49c5-5bdc-48ac-989/odoo-v18-repo/odoo-pooled:latest"
